/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate.mapeos;

import clientes.entity.Clientes;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fermin Velez Bello
 */
public class VentanaDetalle extends javax.swing.JDialog { // JDIALOG para tener modal o no modal

    
    /**
     * Creates new form VentanaDetalle
     */
    ClientesDAO detDAO= new ClientesDAO();
    private String miConsulta; 
    public boolean grabar; // <************ indica a la ventana principal si se ha pinchado el boton grabar o no. SIrve para comuniarrnos con la ventana principal
    PreparedStatement sentenciaPreparada;

    public VentanaDetalle() {
        
       
        this.miConsulta="SELECT NIF,NOMBRE, DIRECCION, TELEFONO from clientes WHERE NIF = ?"; // UN PARAMETRO!! 
        try {
         //   this.sentenciaPreparada= Parametros.PARAM.sentenciaPreparada(miConsulta); // ya tenemos la sentencia preparada...
            
        } catch (Exception ex) {
            Logger.getLogger(VentanaDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
        initComponents();
        
       
     
       this.modoConsulta();  // preparamos la ventana detalle para que por defecto solo sea ver lo que hay.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNIF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTLF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelBotonesConsulta = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelBotonesModifcar = new javax.swing.JPanel();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("AllwaysStayOnTop");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(300, 0, 0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("NIF:");

        jLabel2.setText("Nombre:");

        txtNombre.setName("txtNIF"); // NOI18N

        jLabel3.setText("Dirección:");

        txtDireccion.setName("txtNIF"); // NOI18N

        txtTLF.setName("txtNIF"); // NOI18N

        jLabel4.setText("TLF:");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBotonesConsultaLayout = new javax.swing.GroupLayout(panelBotonesConsulta);
        panelBotonesConsulta.setLayout(panelBotonesConsultaLayout);
        panelBotonesConsultaLayout.setHorizontalGroup(
            panelBotonesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(panelBotonesConsultaLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesConsultaLayout.setVerticalGroup(
            panelBotonesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnGrabar.setToolTipText("Grabar datos");
        btnGrabar.setLabel("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setToolTipText("Cancelar y no grabar");
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesModifcarLayout = new javax.swing.GroupLayout(panelBotonesModifcar);
        panelBotonesModifcar.setLayout(panelBotonesModifcarLayout);
        panelBotonesModifcarLayout.setHorizontalGroup(
            panelBotonesModifcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesModifcarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnGrabar)
                .addGap(80, 80, 80)
                .addComponent(btnCancelar)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelBotonesModifcarLayout.setVerticalGroup(
            panelBotonesModifcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesModifcarLayout.createSequentialGroup()
                .addGroup(panelBotonesModifcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnCancelar))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelBotonesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTLF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(panelBotonesModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelBotonesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotonesModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setVisibleTrue(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_setVisibleTrue
        
     
        
    }//GEN-LAST:event_setVisibleTrue

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
   
        this.setVisible(false); 
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.grabar=false; // no grabar..      
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
         this.grabar=true; // queremos grabar..
        this.setVisible(false);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.grabar=false; // no grabar.. 
    }//GEN-LAST:event_formWindowActivated

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotonesConsulta;
    private javax.swing.JPanel panelBotonesModifcar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNIF;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTLF;
    // End of variables declaration//GEN-END:variables

    void recargaDatos(String nifPinchado) {
        
        Clientes cliente=detDAO.getCliente(nifPinchado);
        this.txtNIF.setText(cliente.getNif());
        this.txtNombre.setText(cliente.getNombre());
        this.txtTLF.setText(cliente.getTelefono());
        this.txtDireccion.setText(cliente.getDireccion());
        
        
        
 /*       try {
            
            this.sentenciaPreparada.setString(1, nifPinchado); // 
            ResultSet filas=this.sentenciaPreparada.executeQuery(); // ya lo hace..sobre la consulta sql con el parametro actualizado
            filas.next(); // solo hay una fila..
            this.txtNIF.setText(filas.getString("nif"));
            this.txtNombre.setText(filas.getString("nombre"));
            this.txtTLF.setText(filas.getString("telefono"));
            this.txtDireccion.setText(filas.getString("direccion"));
            
              
            filas.close();
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaDetalle.class.getName()).log(Level.SEVERE, null, ex);
        } */
        
    }
    
    
    void modoConsulta() // ponemos la ventana en modo consulta: solo se ve el boton cerrar
    {
        this.panelBotonesModifcar.setVisible(false);
        this.panelBotonesConsulta.setVisible(true);
        this.paint(this.getGraphics()); // forzar a que se repinte ... para que no deje cosas colgadas
    
        this.setModal(false); // modo no modal
   

    }
    
        
    void modoEditar() // ponemos la ventana en modo editar : se ven los botones grabar y cancelar
    {
        this.panelBotonesModifcar.setVisible(true);
        this.panelBotonesConsulta.setVisible(false);
      
         this.paint(this.getGraphics());
        this.setModal(true);
    
    }
    
    void limpiaCampos() //inicialia el valor de los textbox que tengo en la ventana.
    {
        this.txtNIF.setText("");
        this.txtNombre.setText("");
        this.txtDireccion.setText("");
        this.txtTLF.setText("");
    }
    
    
    /*
    
      los siguiente m�todos son para obtener los datos que hay en los jTextfield.
    */
    public String getNif () { return this.txtNIF.getText();}
    public String getNombre() {return this.txtNombre.getText();}
    public String getDireccion() { return this.txtDireccion.getText();}
    public String getTlf() { return this.txtTLF.getText();}
}
