/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate.mapeos;



import clientes.entity.Clientes;
import javax.swing.table.DefaultTableModel;
import java.awt.Point;
import java.util.Iterator;
import javax.swing.JOptionPane;
/**
 *
 * @author Fermin Velez Bello
 */
public class VentanaPrincipal extends javax.swing.JFrame {
      String nifPinchado; 

     private DefaultTableModel modelo;  // DECIRLE QUE LA REJILLA USE ESTE MODLO : BOTON DERECHO EN REJILLA-->TABLE CONTENT->CUSTOM ->PONER EL NOMBRE Del atributo , en este caso modelo
    /**
     * Creates new form VentanaPrincipal
     */
    private ClientesDAO cdao=new ClientesDAO();
    
    private VentanaDetalle wDetalle;  
     
    public VentanaPrincipal() {
       
        this.creaModeloRejilla();
        this.cargaDatos();
        this.wDetalle=new VentanaDetalle();   
        
        initComponents();
      
    }
    
    
   public void creaModeloRejilla() 
   {
          this.modelo = new DefaultTableModel() // Esto define el contenido de la rejilla.
                                            // DESCOMENTAR PARA HACER QUE EL CONTENIDO DE LA REJILLA NO SE PUEDA MODIFICAR POR EL OPERADOR
                            { @Override
                                public boolean isCellEditable(int fila, int columna) 
                                    {
                                return false; //Con esto conseguimos que la tabla no se pueda editar
                               }
                             };
        
        
         // a?adirmos las columnas al modelo.
        
     this.modelo.addColumn("NIF");
     this.modelo.addColumn("Nombre");
   }
    
    private void cargaDatos() 
    {
     
         this.modelo.getDataVector().removeAllElements(); // borramos todos los elementos anteriores..
  
         this.modelo=cdao.llenaRejilla(this.modelo);
/*         List<Clientes> listaClientes=cdao.obtenListaContactos();
        
         Iterator<Clientes> lc=listaClientes.iterator();
         
  //       lis.hasNext();
     /*   ResultSet filas;
        
        try {
             filas = Parametros.PARAM.bd.executeQuery("select nif,nombre from clientes" );
      */ 
//Iterator<String> it = lista.iterator();

 /*Clientes cli=(Clientes) lc.next();
 List<Object> clien=(List<Object>) cli;

Iterator c=clien.iterator();
while (c.hasNext()) {


//System.out.println(lc.next().getNif());
//System.out.println(lc.next().getNombre());
Object[] filaNva = {clien.g,cli.getNombre()};
this.modelo.addRow(filaNva);
 
}     */
/*     
             while (lis.hasNext()) {
                // cargamos la fila en la rejilla
                Object filanva=(Object) lis.next();
                   Object[] filaNueva = {filanva.}//{ lis.next().getString("nif"),lis.getString("nombre")}; // creamos un array de objetos del tama?o de las columnas encontradas                 
                  this.modelo.addRow(filaNueva); // a?adirmos fila a fila 
             } 
*/             
      /*   filas.close();
            
        / 
         
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }         
      */  
     }
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      //  entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(null).createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        rejillaDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnIrAlPrincipio = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnIrAlFinal = new javax.swing.JButton();
        btnBorrar = new javax.swing.JToggleButton();
        btnNuevaFila = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rejilla /Detalle");

        rejillaDatos.setModel(modelo);
        rejillaDatos.setToolTipText("");
        rejillaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejillaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rejillaDatos);

        btnIrAlPrincipio.setText("<<");
        btnIrAlPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAlPrincipioActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnIrAlFinal.setText(">>");
        btnIrAlFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAlFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrAlPrincipio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIrAlFinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnIrAlFinal)
                    .addComponent(btnAnterior)
                    .addComponent(btnIrAlPrincipio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBorrar.setText("-");
        btnBorrar.setToolTipText("Borrar fila actual");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnNuevaFila.setText("+");
        btnNuevaFila.setToolTipText("Añadir nueva fila");
        btnNuevaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaFilaActionPerformed(evt);
            }
        });

        btnModificar.setToolTipText("Modificar la fila actual");
        btnModificar.setLabel("#");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevaFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevaFila)
                            .addComponent(btnModificar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnBorrar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
      private String dameElNifPinchado (int fila)
      {
         return  (String) this.rejillaDatos.getModel().getValueAt(fila,0);  
         
      }
    private String dameElNifPinchado (java.awt.event.MouseEvent evt)
    {
        Point p = evt.getPoint();   // da la posici\F3n del click 
        int row = this.rejillaDatos.rowAtPoint(p); // dada la posici\F3n del click en la rejilla nos da la fila.
        return dameElNifPinchado(row);
    }
   
    private void recargaDatos( java.awt.event.MouseEvent evt) //sobrecarga
    {
         this.wDetalle.recargaDatos( this.dameElNifPinchado(evt));
    }
   
    private void recargaDatos(int fila)
    {
       this.wDetalle.recargaDatos( this.dameElNifPinchado(fila));
      
    }
    private void rejillaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejillaDatosMouseClicked
        
            
        if ( evt.getClickCount()== 2)  
                        { 
                             
                            this.recargaDatos(evt);              
                            this.wDetalle.modoConsulta(); // solo boton cerrar
                             this.wDetalle.setVisible(true);
                             return;
                        }
        
        
        if ( this.wDetalle.isVisible()) // si esta visible
                         {
                            this.recargaDatos(evt);                                 
                         }
         
    }//GEN-LAST:event_rejillaDatosMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       int n=this.rejillaDatos.getSelectedRow();
       
       if  ( this.rejillaDatos.getRowCount()-1 == n) return;
       n++;
      this.rejillaDatos.changeSelection( n,1,false,false);      
      if (this.wDetalle.isVisible())  this.recargaDatos(n); 
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnIrAlFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAlFinalActionPerformed
      
      int n=this.rejillaDatos.getSelectedRow();      
      
      if  ( this.rejillaDatos.getRowCount()-1 == n) return;
       
      n=this.rejillaDatos.getRowCount()-1;
      this.rejillaDatos.changeSelection( n,1,false,false);      
      if (this.wDetalle.isVisible()) this.recargaDatos(  n); 
    }//GEN-LAST:event_btnIrAlFinalActionPerformed

    private void btnIrAlPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAlPrincipioActionPerformed
         int n=this.rejillaDatos.getSelectedRow();
       
       if  ( 0 == n) return;
       n=0;
      this.rejillaDatos.changeSelection( n,1,false,false);      
      if (this.wDetalle.isVisible())  this.recargaDatos(n); 
    }//GEN-LAST:event_btnIrAlPrincipioActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
      int n=this.rejillaDatos.getSelectedRow();
       
       if  ( 0 == n) return;
       n--;
      this.rejillaDatos.changeSelection( n,1,false,false);      
      if (this.wDetalle.isVisible())  this.recargaDatos(n);   
    }//GEN-LAST:event_btnAnteriorActionPerformed

    
    /*
    
     BOTON DE BORRADO
    */
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int n=this.rejillaDatos.getSelectedRow();
       
       if  ( n < 0 ) return;       // si no estamos sobre ninguna fila nos vamos.
       
       String nif=this.dameElNifPinchado(n);
       
       

//         ok=true;       
       if (JOptionPane.showConfirmDialog(null,"?Borramos el registro fila con el NIF ='"+nif.trim()+"'?") != JOptionPane.YES_OPTION) return;
        // Clientes cliente; 
        // creamos la instruccion de borrado
         cdao.eliminaCliente(cdao.getCliente(nif));
         this.cargaDatos();
         this.modelo.fireTableDataChanged();      

       
 //      String sql="delete from clientes where nif='"+nif+"'"; // ojo el NIF debe ir entre ' porque para la base de datos es un string
       
       
       
 /*      try {
               System.out.println(sql); // para ver nosostros que esta ejecutando en SQL
        //      Parametros.PARAM.bd.executeUpdate(sql); // la ejectuamos directaemnte
              
              this.cargaDatos(); // recargamos datos
              this.modelo.fireTableDataChanged(); // decimos que han cambiado los datos para que se repinte la rejilla
              
              
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error SQL "+ex.getMessage()+"\n"+sql,"Error SQL",JOptionPane.ERROR_MESSAGE);
          } */
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    /*
    
    INSERTAR NUEVA FILA 
    
    */
    String quotedStr(String s) // muy util
    {
        return "'"+s+"'";
        
    }
    private void btnNuevaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFilaActionPerformed
         
              
         this.wDetalle.modoEditar(); // ahora aparecen los botones de grabar y cancelar y se nos pone en modal
         this.wDetalle.limpiaCampos();// todos los datos en blanco para empezar a editar
         
         boolean ok; // para hace run bucle si da error al grabar el INSERT INTO ...
         
      do
       {   
         this.wDetalle.setVisible(true); // aparece la ventana como MODAL , luego la siguiente linea a esta no se ejecuta hasta que se cierre esa ventana modal.
         
          // preguntamos si quiere grabar o no..
          
          if (!this.wDetalle.grabar) return; // si no quiere grabar nos vamos..              
         
 //        String sql= "insert into clientes  (NIF, NOMBRE, DIRECCION, TELEFONO) VALUES ("  +quotedStr(this.wDetalle.getNif())+","+quotedStr(this.wDetalle.getNombre())
 //                                                                                         +","+quotedStr(this.wDetalle.getDireccion())+","+quotedStr(this.wDetalle.getTlf())
 //                                                                                     +")";
         Clientes cliente=new Clientes(this.wDetalle.getNif(),this.wDetalle.getNombre(),this.wDetalle.getDireccion(),this.wDetalle.getTlf());
         cdao.guardaCliente(cliente);
         this.cargaDatos();
         this.modelo.fireTableDataChanged();
         ok=true;
 /*         try {
               System.out.println(sql); // para ver nosostros que esta ejecutando en SQL
         //     Parametros.PARAM.bd.executeUpdate(sql);// hacemos el insert
              this.cargaDatos(); // recargamos datos
              this.modelo.fireTableDataChanged(); // decimos que han cambiado los datos para que se repinte la rejilla
              ok=true; // todo ok .. nos vamos...
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "Error SQL "+ex.getMessage()+"\n"+sql,"Error SQL",JOptionPane.ERROR_MESSAGE);
              ok= false; // ha fallado ... seguimos otro bucle..
          }*/
       } while (!ok);
         
      
    }//GEN-LAST:event_btnNuevaFilaActionPerformed

    
    /*
    
    MODIFICAR FILA 
    
    
    */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         
        int n=this.rejillaDatos.getSelectedRow();
       
       if  ( n < 0 ) return;       // si no estamos sobre ninguna fila nos vamos.
       
     
         this.wDetalle.modoEditar(); // ahora aparecen los botones de grabar y cancelar y se nos pone en modal
        
         String nifOriginal=this.dameElNifPinchado(n); // guardamos el nif (clave principal) para poder hacer el UPDATE ... WHERE NIF = este nif 
         this.wDetalle.recargaDatos(nifOriginal);// cargamos los datos para este NIF para despues modificarlos
         
         boolean ok; // para hace run bucle si da error al grabar el INSERT INTO ...
         
      do
       {   
         this.wDetalle.setVisible(true); // aparece la ventana como MODAL , luego la siguiente linea a esta no se ejecuta hasta que se cierre esa ventana modal.
         
          // preguntamos si quiere grabar o no..
          
          if (!this.wDetalle.grabar) return; // si no quiere grabar nos vamos..              
         
            
            Clientes cliente=cdao.getCliente(nifOriginal); 
            // actualizan los nuevos valores de las propiedades del obejto cliente 
            cliente.setNif(this.wDetalle.getNif());
            cliente.setNombre(this.wDetalle.getNombre());
            cliente.setDireccion(this.wDetalle.getDireccion());
            cliente.setTelefono(this.wDetalle.getTlf());
            // luego enviamos el objeto a ser actualizado    
            cdao.actualizaCliente(cliente);
            this.cargaDatos(); // recargamos datos
            this.modelo.fireTableDataChanged(); // decimos que han cambiado los datos para que se repinte la rejilla
            ok=true; // todo ok .. nos vamos...
/*         String sql= "update clientes  set NIF="+quotedStr(this.wDetalle.getNif())+","+
                                         "NOMBRE="+quotedStr(this.wDetalle.getNombre()) +",DIRECCION="+quotedStr(this.wDetalle.getDireccion())+
                                         ",TELEFONO="+quotedStr(this.wDetalle.getTlf()) +  
                            " where nif ="+quotedStr(nifOriginal); // <-- where la clave es el nif anterior
                            
                            
          try {
              System.out.println(sql); // para ver nosostros que esta ejecutando en SQL
           //   Parametros.PARAM.bd.executeUpdate(sql);// hacemos el update
              this.cargaDatos(); // recargamos datos
              this.modelo.fireTableDataChanged(); // decimos que han cambiado los datos para que se repinte la rejilla
              ok=true; // todo ok .. nos vamos...
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "Error SQL "+ex.getMessage()+"\n"+sql,"Error SQL",JOptionPane.ERROR_MESSAGE);
              ok= false; // ha fallado ... seguimos otro bucle..
          } */
       } while (!ok);
         
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JToggleButton btnBorrar;
    private javax.swing.JButton btnIrAlFinal;
    private javax.swing.JButton btnIrAlPrincipio;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevaFila;
    private javax.swing.JButton btnSiguiente;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rejillaDatos;
    // End of variables declaration//GEN-END:variables
}
